name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Ejecutar cuando haya cambios en la rama principal
    paths:
      - 'N5Now.Test.Api/**'
      - 'N5Now.Test.Application/**'
      - 'N5Now.Test.Domain/**'
      - 'N5Now.Test.Infrastructure/**'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Get version
        id: vars
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository_owner }}/N5Now.Test.Api:latest \
                       -t ghcr.io/${{ github.repository_owner }}/N5Now.Test.Api:${{ env.VERSION }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/N5Now.Test.Api:latest
          docker push ghcr.io/${{ github.repository_owner }}/N5Now.Test.Api:${{ env.VERSION }}
